CREATE TABLE IF NOT EXISTS `persons` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code_hesabdari` varchar(20) NOT NULL,
  `company` varchar(100) DEFAULT NULL,
  `title` varchar(50) DEFAULT NULL,
  `name` varchar(50) NOT NULL,
  `family` varchar(50) NOT NULL,
  `nickname` varchar(50) DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `type_customer` tinyint(1) DEFAULT 0,
  `type_supplier` tinyint(1) DEFAULT 0,
  `type_shareholder` tinyint(1) DEFAULT 0,
  `type_employee` tinyint(1) DEFAULT 0,
  `credit` decimal(20,2) DEFAULT 0.00,
  `price_list` varchar(50) DEFAULT NULL,
  `tax_type` varchar(50) DEFAULT NULL,
  `tax_registration` varchar(50) DEFAULT NULL,
  `shenase_meli` varchar(20) DEFAULT NULL,
  `code_eghtesadi` varchar(20) DEFAULT NULL,
  `shomare_sabt` varchar(20) DEFAULT NULL,
  `code_shobe` varchar(20) DEFAULT NULL,
  `tozihat` text DEFAULT NULL,
  `address_text` text DEFAULT NULL,
  `country` varchar(50) DEFAULT 'ایران',
  `ostan` varchar(50) DEFAULT NULL,
  `shahr` varchar(50) DEFAULT NULL,
  `codeposti` varchar(10) DEFAULT NULL,
  `telephone` varchar(20) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `fax` varchar(20) DEFAULT NULL,
  `telephone1` varchar(20) DEFAULT NULL,
  `telephone2` varchar(20) DEFAULT NULL,
  `telephone3` varchar(20) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `website` varchar(100) DEFAULT NULL,
  `birth_date` date DEFAULT NULL,
  `marriage_date` date DEFAULT NULL,
  `membership_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_hesabdari` (`code_hesabdari`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_persian_ci;